In [53]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [1]:
obj = pd.Series([4, 7, -5, 3])
print(obj)
print(obj.values)
print(obj.index)  # like range(4)

In [55]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

print(obj2['a'])
print(obj2[['c', 'a', 'd']])
obj2[obj2 > 0]
print(np.exp(obj2))

-5
c    3
a   -5
d    4
dtype: int64
d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [56]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [57]:
'b' in obj2

True

In [58]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata) # create a Serise
print(obj3)


states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
print(obj4)
print(pd.isnull(obj4))
print(pd.notnull(obj4))
print(obj3 + obj4)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64
California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool
California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool
California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [59]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
print(frame)
print(frame.state[:])
print(pd.DataFrame(data, columns=['year', 'state', 'pop']))

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2
0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object
   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [60]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four','five', 'six'])

print(frame2)
print(frame2.loc['three'])
frame2['debt'] = 16.5
print(frame2.loc['three'])
frame2['debt'] = np.arange(6.)
print(frame2.loc['three'])

val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
print(val)
frame2['debt'] = val
print(frame2['debt'])
frame2.index
isinstance(val, pd.Series)

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN
year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object
year     2002
state    Ohio
pop       3.6
debt     16.5
Name: three, dtype: object
year     2002
state    Ohio
pop       3.6
debt      2.0
Name: three, dtype: object
two    -1.2
four   -1.5
five   -1.7
dtype: float64
one      NaN
two     -1.2
three    NaN
four    -1.5
five    -1.7
six      NaN
Name: debt, dtype: float64

True

In [61]:
print(frame2.columns)
print(frame2.index)
print(frame2['year']['one'])
frame2['newcolumn']  = (frame2['year'] == 2000)
print(frame2)

Index(['year', 'state', 'pop', 'debt'], dtype='object')
Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')
2000
       year   state  pop  debt  newcolumn
one    2000    Ohio  1.5   NaN       True
two    2001    Ohio  1.7  -1.2      False
three  2002    Ohio  3.6   NaN      False
four   2001  Nevada  2.4  -1.5      False
five   2002  Nevada  2.9  -1.7      False
six    2003  Nevada  3.2   NaN      False

In [62]:
del frame2['year']
frame2

        state  pop  debt  newcolumn
one      Ohio  1.5   NaN       True
two      Ohio  1.7  -1.2      False
three    Ohio  3.6   NaN      False
four   Nevada  2.4  -1.5      False
five   Nevada  2.9  -1.7      False
six    Nevada  3.2   NaN      False

In [63]:
from collections import defaultdict
dic=defaultdict(list)
dic[1]=np.arange(100)
print(dic[1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

In [64]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame_pop = pd.DataFrame(pop)
frame_pop

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [65]:
frame_pop.T

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [66]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [67]:
frame_pop["Nevada"][2002]
# frame_pop[2002]["Nevada"] error

2.9

In [68]:
frame_pop.index.name ="year"
frame_pop.columns.name ="state"
print(frame_pop)
print(frame_pop.values)

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5
[[2.4 1.7]
 [2.9 3.6]
 [nan 1.5]]

In [69]:
val1 = pd.Series([1, 2 ,3], index=[2000, 2001, 2002])

frame_pop["new"]=val1
frame_pop

state  Nevada  Ohio  new
year
2001      2.4   1.7    2
2002      2.9   3.6    3
2000      NaN   1.5    1

In [70]:
new_row =pd.DataFrame( {'Nevada': {1997:1}, 'Ohio': {1997:1}, 'new': {1997:1}})
frame_pop1=  pd.concat([frame_pop, new_row])
frame_pop1

      Nevada  Ohio  new
2001     2.4   1.7    2
2002     2.9   3.6    3
2000     NaN   1.5    1
1997     1.0   1.0    1

In [71]:
new_row =pd.DataFrame( {'Nevada': {1997:1}, 'Ohio': {1998:1}, 'new': {1997:1}})
frame_pop1=  pd.concat([frame_pop, new_row])
frame_pop1

      Nevada  Ohio  new
2001     2.4   1.7  2.0
2002     2.9   3.6  3.0
2000     NaN   1.5  1.0
1997     1.0   NaN  1.0
1998     NaN   1.0  NaN

In [72]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four','five', 'six'])
frame2['year']['one']
frame2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [73]:
frame_pop1
print(frame_pop1.loc[2001])
frame_pop1.drop(2002)

Nevada    2.4
Ohio      1.7
new       2.0
Name: 2001, dtype: float64

      Nevada  Ohio  new
2001     2.4   1.7  2.0
2000     NaN   1.5  1.0
1997     1.0   NaN  1.0
1998     NaN   1.0  NaN

In [74]:
labels = pd.Index(np.arange(2000, 2030, 10))
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
print(obj2 )

2000    1.5
2010   -2.5
2020    0.0
dtype: float64

In [75]:
2000 in obj2.index

True

In [76]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[2, 0, 4])
obj3.reindex

<bound method Series.reindex of 2      blue
0    purple
4    yellow
dtype: object>

In [77]:
frame= pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
print(frame2)

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [78]:
frame2[['Ohio', 'Texas']]
frame2['Ohio'][:2]
print(frame2['Ohio']>2)
print(frame2[frame2['Ohio']>2])
print('\n')
print(frame2[:1]>0)
print(frame2[frame2[:2]>2])
print(frame2>5)
frame2[frame2>5]=0
frame2

a    False
b    False
c     True
d     True
Name: Ohio, dtype: bool
   Ohio  Texas  California
c   3.0    4.0         5.0
d   6.0    7.0         8.0


    Ohio  Texas  California
a  False   True        True
   Ohio  Texas  California
a   NaN    NaN         NaN
b   NaN    NaN         NaN
c   NaN    NaN         NaN
d   NaN    NaN         NaN
    Ohio  Texas  California
a  False  False       False
b  False  False       False
c  False  False       False
d   True   True        True

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   0.0    0.0         0.0

In [79]:
# loc  iloc
print(frame2.iloc[[1],[0,1]]) # =
frame2.iloc[1,:2]

   Ohio  Texas
b   NaN    NaN

Ohio    NaN
Texas   NaN
Name: b, dtype: float64

In [80]:
frame= pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])
frame2.loc[:'b','Ohio']

a    0.0
b    NaN
Name: Ohio, dtype: float64

In [81]:
# !conda install pandas
import pandas as pd
import numpy as np 
df1=pd.DataFrame(np.arange(12).reshape(3,4), index=list('bcd'), columns=['Ohio', 'Texas', 'Colorado','a'])
df2=pd.DataFrame(np.arange(6).reshape(3,2), index=list('bcd'), columns=['Ohio', 'Texas'])

print(df1)
print(df2)
print(df1+df2)

   Ohio  Texas  Colorado   a
b     0      1         2   3
c     4      5         6   7
d     8      9        10  11
   Ohio  Texas
b     0      1
c     2      3
d     4      5
   Colorado  Ohio  Texas   a
b       NaN     0      2 NaN
c       NaN     6      8 NaN
d       NaN    12     14 NaN

In [82]:
df1 = pd.DataFrame({"a":[1,2], "b":[3,4]})
df2 = pd.DataFrame({"c":[6,7], "b":[10, 11]})

df1 - df2

    a  b   c
0 NaN -7 NaN
1 NaN -7 NaN

In [83]:
df1 = pd.DataFrame(np.arange(12).reshape(3,4), index=list('abc'), columns=list('qwer'))
df2 = pd.DataFrame(np.arange(20).reshape(4,5), index=list('abcd'), columns=list('qwert'))

print(df1+df2)
df1.add(df2,fill_value=0)

      e     q     r   t     w
a   4.0   0.0   6.0 NaN   2.0
b  13.0   9.0  15.0 NaN  11.0
c  22.0  18.0  24.0 NaN  20.0
d   NaN   NaN   NaN NaN   NaN

      e     q     r     t     w
a   4.0   0.0   6.0   4.0   2.0
b  13.0   9.0  15.0   9.0  11.0
c  22.0  18.0  24.0  14.0  20.0
d  17.0  15.0  18.0  19.0  16.0

In [84]:
print(df1,'\n',df2)
df1.reindex(columns=df2.columns, fill_value=0)
df1.reindex(columns=list('qwertyu'), index=list('abcs'), fill_value=0)

   q  w   e   r
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11
     q   w   e   r   t
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19

   q  w   e   r  t  y  u
a  0  1   2   3  0  0  0
b  4  5   6   7  0  0  0
c  8  9  10  11  0  0  0
s  0  0   0   0  0  0  0

In [85]:
# interact between Series and DataFrame
df2 = pd.DataFrame(np.arange(20).reshape(4,5), index=list('abcd'), columns=list('qwert'))

se1 = df2.iloc[1,:]
print(se1)
print(df2)
print(df2-se1)

q    5
w    6
e    7
r    8
t    9
Name: b, dtype: int32
    q   w   e   r   t
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
    q   w   e   r   t
a  -5  -5  -5  -5  -5
b   0   0   0   0   0
c   5   5   5   5   5
d  10  10  10  10  10

In [88]:
df2 = pd.DataFrame(np.arange(20).reshape(4,5), index=list('abcd'), columns=list('qwert'))

se2 = df2.iloc[:,1]
print(se2)
df3 = df2.sub(se2, axis='index')
df3 = df2.sub(se2, axis='columns')
print(df2,"\n", df3)

a     1
b     6
c    11
d    16
Name: w, dtype: int32
    q   w   e   r   t
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
     a   b   c   d   e   q   r   t   w
a NaN NaN NaN NaN NaN NaN NaN NaN NaN
b NaN NaN NaN NaN NaN NaN NaN NaN NaN
c NaN NaN NaN NaN NaN NaN NaN NaN NaN
d NaN NaN NaN NaN NaN NaN NaN NaN NaN

In [91]:
f = lambda x: x.max() - x.min()

df2.apply(f, axis = 'columns')

a    4
b    4
c    4
d    4
dtype: int64

In [96]:
def f(x):
    return pd.Series([x.max() , x.min()], index= ['max', 'min'])

print(df2)
df2.apply(f,axis='columns')
#df2.apply(f,axis='index')

    q   w   e   r   t
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19

   max  min
a    4    0
b    9    5
c   14   10
d   19   15

In [97]:
f = lambda x: float(x)

df2.applymap(f)

      q     w     e     r     t
a   0.0   1.0   2.0   3.0   4.0
b   5.0   6.0   7.0   8.0   9.0
c  10.0  11.0  12.0  13.0  14.0
d  15.0  16.0  17.0  18.0  19.0

In [107]:
df4 = pd.DataFrame(np.arange(12).reshape((4,3)), columns =list('acd'),index=list('3124'))

print(df4)        

df4.sort_index
df4.sort_index(ascending=False)
print(df4.sort_values)
print(df4.sort_values(by=['c','a']))

   a   c   d
3  0   1   2
1  3   4   5
2  6   7   8
4  9  10  11
<bound method DataFrame.sort_values of    a   c   d
3  0   1   2
1  3   4   5
2  6   7   8
4  9  10  11>
   a   c   d
3  0   1   2
1  3   4   5
2  6   7   8
4  9  10  11

In [108]:
df4.sum(axis='index')

a    18
c    22
d    26
dtype: int64

In [109]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj.index.is_unique

False

In [110]:
obj.mean

<bound method NDFrame._add_numeric_operations.<locals>.mean of a    0
a    1
b    2
b    3
c    4
dtype: int64>

In [111]:
df2.describe()

               q          w          e          r          t
count   4.000000   4.000000   4.000000   4.000000   4.000000
mean    7.500000   8.500000   9.500000  10.500000  11.500000
std     6.454972   6.454972   6.454972   6.454972   6.454972
min     0.000000   1.000000   2.000000   3.000000   4.000000
25%     3.750000   4.750000   5.750000   6.750000   7.750000
50%     7.500000   8.500000   9.500000  10.500000  11.500000
75%    11.250000  12.250000  13.250000  14.250000  15.250000
max    15.000000  16.000000  17.000000  18.000000  19.000000

In [113]:
se1.describe()

count    5.000000
mean     7.000000
std      1.581139
min      5.000000
25%      6.000000
50%      7.000000
75%      8.000000
max      9.000000
Name: b, dtype: float64

In [132]:
### code is here ###
import pandas_datareader as web
import time
import datetime as dt
import pandas as pd


start=dt.datetime(2010,1,1)
end=dt.datetime(2017,1,1)
df = yf.download(tickers=['^GSPC'], start=start, end=end)

NameError: name 'startDate' is not defined

In [133]:
obj.value_counts()

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [135]:
csv1 = pd.read_csv('try.csv')
print(csv1)

csv1 = pd.read_csv('try.csv',header=None)
print(csv1)

  Unnamed: 0  a  b  c
0          z  1  2  3
1          x  1  2  3
2          c  1  2  3
3          v  1  2  3
4          b  1  2  3
     0  1  2  3
0  NaN  a  b  c
1    z  1  2  3
2    x  1  2  3
3    c  1  2  3
4    v  1  2  3
5    b  1  2  3

In [190]:
csv1 = pd.read_csv('try.csv', names = ['name','a','b','c'],index_col='name')
print(csv1)

      a  b  c
name
NaN   a  b  c
z     1  2  3
x     1  2  3
c     1  2  3
v     1  2  3
b     1  2  3

In [157]:
csv1 = pd.read_csv('try.csv', names = ['name','a','b','c'],index_col='name', skiprows=[0])
print(csv1)

      a  b  c
name
z     1  2  3
x     1  2  3
c     1  2  3
v     1  2  3
b     1  2  3

In [179]:
csv1 = pd.read_csv('try.csv', skiprows=[4] , header = 2 , names = ['name','a','b','c'],index_col='name', na_values=['NULL'])
print(csv1)

      a  b  c
name
c     1  2  3
b     1  2  3

In [174]:
csv1 = pd.read_csv('try.csv', nrows=3)
print(csv1)

  Unnamed: 0  a  b  c
0          z  1  2  3
1          x  1  2  3
2          c  1  2  3

In [177]:
# Specify the chunk size (number of rows per chunk)
chunk_size = 1000

csv_chunks = pd.read_csv('try.csv', header=1, chunksize=chunk_size)

with open('try.csv', 'r') as csvfile:
    header = csvfile.readline().strip().split(',')


print("Header:", header)

for chunk in csv_chunks:
    # Perform your data processing or analysis on each chunk
    print("Data chunk:")
    print(chunk.to_numpy().tolist())

Header: ['\ufeff', 'a', 'b', 'c']
Data chunk:
[['x', 1, 2, 3], ['c', 1, 2, 3], ['v', 1, 2, 3], ['b', 1, 2, 3]]

In [182]:
import sys
csv1.to_csv('tryout.csv')
csv1.to_csv(sys.stdout, index=False, header=False)

1,2,3
1,2,3

In [183]:
csv1.to_csv(sys.stdout, index=False, columns=['a', 'b', 'c'])

a,b,c
1,2,3
1,2,3

In [194]:
import csv

csv2 = csv.reader(open('try.csv'))

for line in csv2:
    print(line)

print(csv2)

['\ufeff', 'a', 'b', 'c']
['z', '1', '2', '3']
['x', '1', '2', '3']
['c', '1', '2', '3']
['v', '1', '2', '3']
['b', '1', '2', '3']
<_csv.reader object at 0x00000274425E7A00>

In [218]:
import json



with open('obj.json','r') as f:
    data = json.loads(f.read())


df = pd.json_normalize(
    data,
    record_path =['students'],
    meta=[
        'class',
        ['info', 'president'],
        ['info', 'address'],
        ['info', 'contacts', 'tel']
    ]
)

print(df)
print(df.to_json())

     id   name  math  physics  chemistry   class info.president  \
0  A001    Tom    60       66         61  Year 1    John Kasich
1  A002  James    89       76         51  Year 1    John Kasich
2  A003  Jenny    79       90         78  Year 1    John Kasich

           info.address info.contacts.tel
0  ABC road, London, UK         123456789
1  ABC road, London, UK         123456789
2  ABC road, London, UK         123456789
{"id":{"0":"A001","1":"A002","2":"A003"},"name":{"0":"Tom","1":"James","2":"Jenny"},"math":{"0":60,"1":89,"2":79},"physics":{"0":66,"1":76,"2":90},"chemistry":{"0":61,"1":51,"2":78},"class":{"0":"Year 1","1":"Year 1","2":"Year 1"},"info.president":{"0":"John Kasich","1":"John Kasich","2":"John Kasich"},"info.address":{"0":"ABC road, London, UK","1":"ABC road, London, UK","2":"ABC road, London, UK"},"info.contacts.tel":{"0":"123456789","1":"123456789","2":"123456789"}}

In [219]:
# read_html
!conda install lxml

^C

In [ ]:
!pip install beautifulsoup4 html5lib

In [225]:
df = pd.read_html('https://commons.wikimedia.org/wiki/Main_Page')
print(df)
len(df)
print(df[0].head())

[                                                   0  \
0  Wikimedia Commonsa collection of 95,738,983 fr...

                             1
0  Images Sounds Videos Upload  ,                                                    0  \
0  Picture of the day  A brewery in California. T...

                                                   1
0  Monthly photo challenge  Take some photos and ...  ]
                                                   0  \
0  Wikimedia Commonsa collection of 95,738,983 fr...

                             1
0  Images Sounds Videos Upload

In [ ]:
from lxml import objectify

# activeta a env name Jupyter